"""add collabrative and notifcation table

Revision ID: 3de9d24ecb40
Revises: 33b2a0bfc9de
Create Date: 2024-09-03 19:59:28.937626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de9d24ecb40'
down_revision = '33b2a0bfc9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_messages_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_group_id'))

    op.drop_table('group_messages')
    # ### end Alembic commands ###
