"""empty message

Revision ID: a4e052d601f6
Revises: 3de9d24ecb40
Create Date: 2024-12-25 15:53:03.011176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e052d601f6'
down_revision = '3de9d24ecb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
